### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [bojanaobrenovic/RelativeAzimuthAndDistance#1]
@bojanaobrenovic  we would be happy to publish your plugin but please make sure that we can see the source code in this repository

**Comment by bojanaobrenovic** [comment]
Hello,

Sorry. Try it now, please.  You should now be able to see the source code.

Best regards!

**Comment by NyakudyaA** [comment]
@bojanaobrenovic Please remove .pyc files they are generated automatically
